"use client";

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Info, Bot, Download, Code, Zap, Settings, ShieldCheck, Plus, Trash2, Search, Server} from 'lucide-react';
import styles from './page.module.css';
import { toast } from 'react-hot-toast';

type TabType = 'agent' | 'catalog' | 'mcp' | 'llms' | 'llms-full' | 'policy' | 'ai-plugin' | 'openapi' | 'robots';

export default function AgenticSEOAdvanced() {
  const [siteName, setSiteName] = useState('example.com');
  const [description, setDescription] = useState('A premium ecommerce platform.');
  
  const [skills, setSkills] = useState([
    { name: 'search_products', method: 'GET', endpoint: '/api/products', desc: 'Search catalog' },
    { name: 'create_order', method: 'POST', endpoint: '/api/orders', desc: 'Place a new order' }
  ]);

  const [activeTab, setActiveTab] = useState<TabType>('agent');
  const [isScanning, setIsScanning] = useState(false);

  // Generate Files Data
  const agentCard = {
    "@context": "https://schema.org/",
    "@type": "WebSite",
    "name": siteName,
    "description": description,
    "agentCapabilities": {
      "supportedActions": skills.map(s => s.name),
      "apiCatalog": "/.well-known/api-catalog",
      "mcpServer": "/.well-known/mcp/server-card.json"
    }
  };

  const apiCatalog = {
    "openapi": "3.1.0",
    "info": {
      "title": `${siteName} API Catalog for Agents`,
      "version": "1.0.0"
    },
    "paths": skills.reduce((acc: any, skill) => {
      acc[skill.endpoint] = {
        [skill.method.toLowerCase()]: {
          "operationId": skill.name,
          "summary": skill.desc,
          "responses": { "200": { "description": "Success" } }
        }
      };
      return acc;
    }, {})
  };

  const mcpServer = {
    "server": {
      "name": `${siteName}-mcp`,
      "version": "1.0.0",
      "protocol": "stdio",
      "capabilities": {
        "tools": skills.map(s => ({
          "name": s.name,
          "description": s.desc
        }))
      }
    }
  };

  const llmsTxt = `# ${siteName}
> ${description}

## Available Tools (APIs)
${skills.map(s => `- **${s.name}**: ${s.desc} (\`${s.method} ${s.endpoint}\`)`).join('\n')}

_This file was automatically generated by AutoSEO Pro for LLM parsing._
`;

  const llmsFullTxt = `# ${siteName} - Full AI Context
> ${description}

## Comprehensive API Documentation
${skills.map(s => `### ${s.name}\n- **Endpoint:** \`${s.method} ${s.endpoint}\`\n- **Description:** ${s.desc}\n- **Parameters:** (Automatically mapped via OpenAPI)`).join('\n\n')}

## Business Rules & Context
- All prices are in USD.
- User data is protected by GDPR compliance.
- Support available 24/7.

_This full documentation endpoint provides deep context for autonomous reasoning._
`;

  const policyTxt = `User-Agent: AI-Agent
Allow: /.well-known/api-catalog
Allow: /.well-known/mcp/
Disallow: /private/
Disallow: /admin/

# AI Data Usage Policy
We allow ethical AI agents to crawl and interact with public endpoints for user assistance. Data scraping for model training is prohibited without prior consent.
`;

  const aiPlugin = {
    "schema_version": "v1",
    "name_for_human": siteName,
    "name_for_model": siteName.replace(/[^a-zA-Z0-9]/g, ''),
    "description_for_human": description,
    "description_for_model": `Plugin for interacting with ${siteName}. Endpoints: ${skills.map(s => s.endpoint).join(', ')}`,
    "auth": { "type": "none" },
    "api": {
      "type": "openapi",
      "url": `https://${siteName}/.well-known/openapi.json`
    },
    "logo_url": `https://${siteName}/logo.png`,
    "contact_email": `support@${siteName}`,
    "legal_info_url": `https://${siteName}/legal`
  };

  const robotsTxt = `# AI/LLM Bot Configurations
User-agent: GPTBot
Disallow: /private/
Allow: /api/

User-agent: Google-Extended
Disallow: /private/

User-agent: Claude-Web
Disallow: /private/

User-agent: CCBot
Disallow: /

# General Search Engines
User-agent: *
Allow: /
Sitemap: https://${siteName}/sitemap.xml
`;

  const openapiJson = {
    "openapi": "3.0.1",
    "info": {
      "title": `${siteName} AI Plugin API`,
      "description": description,
      "version": "1.0.0"
    },
    "servers": [{ "url": `https://${siteName}` }],
    "paths": skills.reduce((acc: any, skill) => {
      acc[skill.endpoint] = {
        [skill.method.toLowerCase()]: {
          "operationId": skill.name,
          "summary": skill.desc,
          "responses": { "200": { "description": "Successful operation" } }
        }
      };
      return acc;
    }, {})
  };

  const addSkill = () => {
    setSkills([...skills, { name: 'new_skill', method: 'GET', endpoint: '/api/new', desc: 'Description' }]);
  };

  const removeSkill = (index: number) => {
    setSkills(skills.filter((_, i) => i !== index));
  };

  const updateSkill = (index: number, field: string, value: string) => {
    const newSkills = [...skills];
    newSkills[index] = { ...newSkills[index], [field]: value };
    setSkills(newSkills);
  };

  const handleScan = () => {
    setIsScanning(true);
    setTimeout(() => {
      setSkills([
        ...skills,
        { name: 'get_pricing', method: 'GET', endpoint: '/api/pricing', desc: 'Fetch latest prices' }
      ]);
      setIsScanning(false);
      toast.success('Found 1 new API endpoint!');
    }, 1500);
  };

  const getActiveData = () => {
    switch (activeTab) {
      case 'agent': return { data: JSON.stringify(agentCard, null, 2), name: 'agent-card.json', type: 'text/json' };
      case 'catalog': return { data: JSON.stringify(apiCatalog, null, 2), name: 'api-catalog.json', type: 'text/json' };
      case 'mcp': return { data: JSON.stringify(mcpServer, null, 2), name: 'server-card.json', type: 'text/json' };
      case 'ai-plugin': return { data: JSON.stringify(aiPlugin, null, 2), name: 'ai-plugin.json', type: 'text/json' };
      case 'openapi': return { data: JSON.stringify(openapiJson, null, 2), name: 'openapi.json', type: 'text/json' };
      case 'robots': return { data: robotsTxt, name: 'robots.txt', type: 'text/plain' };
      case 'llms-full': return { data: llmsFullTxt, name: 'llms-full.txt', type: 'text/plain' };
      case 'policy': return { data: policyTxt, name: 'policies.txt', type: 'text/plain' };
      default: return { data: llmsTxt, name: 'llms.txt', type: 'text/plain' };
    }
  };

  const handleDownload = () => {
    const { data, name, type } = getActiveData();
    const dataStr = `data:${type};charset=utf-8,` + encodeURIComponent(data);
    const a = document.createElement('a');
    a.href = dataStr;
    a.download = name;
    a.click();
    toast.success(`Downloaded ${name}`);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={styles.container}
    >
      <div className={styles.header}>
        <div>
          <h1 className={styles.title}><Bot color="#5A4AF4" size={32} /> Advanced Agentic SEO</h1>
          <p className={styles.subtitle}>
            Enterprise-grade configuration for Autonomous Agents. Define APIs, skills, and MCP protocols natively.
          </p>
      {/* Auto-injected Info Block */}
      <div style={{ background: '#F0F9FF', border: '1px solid #BAE6FD', padding: '1rem', borderRadius: '8px', marginBottom: '1.5rem', display: 'flex', gap: '12px' }}>
        <Info size={20} color="#0284C7" style={{ flexShrink: 0, marginTop: '2px' }} />
        <div>
          <h4 style={{ margin: '0 0 0.5rem 0', color: '#0369A1', fontSize: '0.95rem' }}>How does this work?</h4>
          <p style={{ margin: 0, color: '#0C4A6E', fontSize: '0.85rem', lineHeight: '1.5' }}>
             Prepares your website for AI bots (like ChatGPT, Claude). It generates configuration files (like llms.txt) so AI models can read your content and recommend you. <strong>Example:</strong> When someone asks ChatGPT "What is the best SEO tool?", providing an agent-card helps ChatGPT understand your site and recommend it.
          </p>
        </div>
      </div>
  
        </div>
        <div className={styles.headerActions}>
          <button onClick={handleScan} className={styles.secondaryBtn} disabled={isScanning}>
            {isScanning ? <Zap className="animate-spin" size={18} /> : <Search size={18} />}
            {isScanning ? 'Scanning...' : 'Auto-Discover APIs'}
          </button>
          <button onClick={handleDownload} className={styles.primaryBtn}>
            <Download size={18} /> Export Package
          </button>
        </div>
      </div>

      <div className={styles.grid}>
        {/* Left Column: Visual Builder */}
        <div className={styles.card}>
          <h2 className={styles.cardTitle}><Settings size={20} color="#A855F7" /> Agent Identity Setup</h2>
          
          <div className={styles.inputGroup}>
            <label className={styles.label}>Identity Name</label>
            <input 
              type="text" 
              className={styles.input} 
              value={siteName} 
              onChange={(e) => setSiteName(e.target.value)} 
            />
          </div>
          
          <div className={styles.inputGroup}>
            <label className={styles.label}>Agent Persona / Description</label>
            <textarea 
              className={styles.textarea} 
              value={description} 
              onChange={(e) => setDescription(e.target.value)} 
            />
          </div>

          <h2 className={styles.cardTitle} style={{ marginTop: '1rem', marginBottom: '1rem' }}><Server size={20} color="#10B981" /> API Skills Builder</h2>
          
          <div className={styles.skillsContainer}>
            <AnimatePresence>
              {skills.map((skill, i) => (
                <motion.div 
                  initial={{ opacity: 0, height: 0 }} 
                  animate={{ opacity: 1, height: 'auto' }} 
                  exit={{ opacity: 0, height: 0 }} 
                  key={i} 
                  className={styles.skillItem}
                >
                  <select 
                    className={styles.skillMethod + (skill.method === 'POST' ? ' ' + styles.post : '')} 
                    value={skill.method}
                    onChange={(e) => updateSkill(i, 'method', e.target.value)}
                    style={{ border: 'none', outline: 'none' }}
                  >
                    <option value="GET">GET</option>
                    <option value="POST">POST</option>
                  </select>
                  
                  <div className={styles.skillInfo}>
                    <input 
                      type="text" 
                      value={skill.name} 
                      onChange={(e) => updateSkill(i, 'name', e.target.value)}
                      style={{ background: 'transparent', border: 'none', color: '#0F172A', fontWeight: 600, fontSize: '0.85rem', outline: 'none', width: '100%' }}
                    />
                    <input 
                      type="text" 
                      value={skill.endpoint} 
                      onChange={(e) => updateSkill(i, 'endpoint', e.target.value)}
                      style={{ background: 'transparent', border: 'none', color: '#64748B', fontFamily: 'monospace', fontSize: '0.75rem', outline: 'none', width: '100%', marginTop: '2px' }}
                    />
                  </div>
                  <button onClick={() => removeSkill(i)} style={{ background: 'transparent', border: 'none', color: '#EF4444', cursor: 'pointer', padding: '4px' }}>
                    <Trash2 size={16} />
                  </button>
                </motion.div>
              ))}
            </AnimatePresence>
            <button onClick={addSkill} className={styles.addSkillBtn}>
              <Plus size={16} /> Add Custom Skill
            </button>
          </div>
        </div>

        {/* Right Column: Code Generation */}
        <div className={styles.card}>
          <div className={styles.tabs} style={{ flexWrap: 'wrap' }}>
            <button className={`${styles.tab} ${activeTab === 'agent' ? styles.active : ''}`} onClick={() => setActiveTab('agent')}>agent-card</button>
            <button className={`${styles.tab} ${activeTab === 'catalog' ? styles.active : ''}`} onClick={() => setActiveTab('catalog')}>api-catalog</button>
            <button className={`${styles.tab} ${activeTab === 'mcp' ? styles.active : ''}`} onClick={() => setActiveTab('mcp')}>mcp-server</button>
            <button className={`${styles.tab} ${activeTab === 'llms' ? styles.active : ''}`} onClick={() => setActiveTab('llms')}>llms.txt</button>
            <button className={`${styles.tab} ${activeTab === 'llms-full' ? styles.active : ''}`} onClick={() => setActiveTab('llms-full')}>llms-full.txt</button>
            <button className={`${styles.tab} ${activeTab === 'policy' ? styles.active : ''}`} onClick={() => setActiveTab('policy')}>policies.txt</button>
            <button className={`${styles.tab} ${activeTab === 'ai-plugin' ? styles.active : ''}`} onClick={() => setActiveTab('ai-plugin')}>ai-plugin</button>
            <button className={`${styles.tab} ${activeTab === 'openapi' ? styles.active : ''}`} onClick={() => setActiveTab('openapi')}>openapi</button>
            <button className={`${styles.tab} ${activeTab === 'robots' ? styles.active : ''}`} onClick={() => setActiveTab('robots')}>AI robots.txt</button>
          </div>
          
          <pre className={styles.codeBlock}>
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, x: 10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.2 }}
            >
              {getActiveData().data}
            </motion.div>
          </pre>

          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1rem', padding: '1rem', background: 'rgba(90,74,244,0.1)', border: '1px solid rgba(90,74,244,0.2)', borderRadius: '8px' }}>
            <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
              <Code size={20} color="#A5B4FC" />
              <div>
                <div style={{ fontSize: '0.85rem', fontWeight: 600, color: '#0F172A' }}>Next.js Integration</div>
                <div style={{ fontSize: '0.75rem', color: '#64748B' }}>Copy this code to your <code>app/.well-known/</code> route.</div>
              </div>
            </div>
            <button className={styles.secondaryBtn} style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
              Copy Route Code
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
